hashkit: fix missing-prototype errors
When building with -Wall -Werror these are raised by the compiler:

   dyn_murmur.c:44:1: error: no previous prototype for ‘hash_murmur’
   dyn_one_at_a_time.c:41:1: error: no previous prototype for ‘hash_one_at_a_time’
   dyn_murmur3.c:30:1: error: no previous prototype for ‘hash_murmur3’

Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>