hashkit/md5: fix build errors: -Werror=conversion -Werror=missing-prototypes
MD5_* symbols are not used outside, hence were marked as static.

Conversion errors addressed with proper casts.

Fixes these build problems:

dyn_md5.c:203:1: error: no previous prototype for ‘MD5_Init’ [-Werror=missing-prototypes]
 MD5_Init(MD5_CTX *ctx)
dyn_md5.c:224:16: error: conversion to ‘MD5_u32plus {aka unsigned int}’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
     ctx->hi += size >> 29;
dyn_md5.c:284:17: error: conversion to ‘unsigned char’ from ‘MD5_u32plus {aka unsigned int}’ may alter its value [-Werror=conversion]
     result[2] = ctx->a >> 16;

Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>