seedsprovider/florida: tmpres should be ssize_t
tmpres is used for storing send()/recv() return values, which are of ssize_t
type. Converting to uint32_t made return value checks always false.

Fixes:

dyn_florida.c:124:19: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         if(tmpres == -1){
                   ^~
dyn_florida.c:175:15: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     if(tmpres < 0) {

Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>