seedsprovider/dns: sizeof() returns size_t which is unsigned
Fixes:

dyn_dns.c:93:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (qr >= sizeof(buf)) {

Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>