hashkit/crc32: fix conversion/prototype mismatch
hash_crc32a() is declared to return rstatus_t, not uint32_t.

Add proper casts where required.

Fixes:

dyn_crc32.c:143:70: error: conversion to ‘uint32_t {aka unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
 #define _CRC32_(crc, ch)     ((crc) = ((crc) >> 8) ^ crc32tab[((crc) ^ (ch)) &\
dyn_crc32.c:155:14: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
     for (len += nr, p = buf; nr--; ++p)
dyn_crc32.c:146:1: error: conflicting types for ‘crc32_sz’
 crc32_sz(const char *buf, int buf_length, uint32_t in_crc32)

Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>